version: '3'

volumes:
  static_volume:
  media_volume:
  pg_data_production:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: ddimani/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/static
      - media_volume:/media
  frontend:
    image: ddimani/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    image: ddimani/foodgram_gateway
    depends_on:
      - backend
      - frontend
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static_volume:/static
      - media_volume:/media
