version: '3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: foodgram
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: foodgram_password
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    environment:
      POSTGRES_DB: foodgram
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: foodgram_password
      DB_HOST: db
      DB_PORT: 5432
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media

  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    build: ./infra/
    env_file: .env
    depends_on:
      - backend
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
      - media:/media