# Generated by Django 4.2.20 on 2025-04-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_options_recipe_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name', 'measurement_unit'), 'verbose_name': 'ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'ordering': ('name', 'recipe'), 'verbose_name': 'ингредиент в рецепте', 'verbose_name_plural': 'Ингредиенты в рецепте'},
        ),
        migrations.RemoveConstraint(
            model_name='ingredientrecipe',
            name='unique_recipe_ingredient',
        ),
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='ingredient',
            new_name='name',
        ),
        migrations.AddConstraint(
            model_name='ingredientrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'name'), name='unique_recipe_ingredient'),
        ),
    ]
