# Generated by Django 4.2.20 on 2025-04-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'ordering': ('ingredient', 'recipe'), 'verbose_name': 'ингредиент в рецепте', 'verbose_name_plural': 'Ингредиенты в рецепте'},
        ),
        migrations.RemoveConstraint(
            model_name='ingredientrecipe',
            name='unique_recipe_ingredient',
        ),
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='name',
            new_name='ingredient',
        ),
        migrations.AddConstraint(
            model_name='ingredientrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
    ]
